# Generated by Django 2.1.2 on 2019-01-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-id']},
        ),
    ]
