# Generated by Django 2.1.2 on 2019-01-15 12:41

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_file_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='moviefile',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='moviefile',
            name='dateFolderPath',
        ),
        migrations.RemoveField(
            model_name='moviefile',
            name='fileName',
        ),
        migrations.RemoveField(
            model_name='moviefile',
            name='folder',
        ),
        migrations.AlterField(
            model_name='moviefile',
            name='file',
            field=models.FileField(blank=True, default='', upload_to=movie.models.path_and_rename),
        ),
    ]
