# Generated by Django 2.1.2 on 2019-01-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_classification_movieclassificationbridge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieclassificationbridge',
            name='classification_id',
        ),
        migrations.RemoveField(
            model_name='movieclassificationbridge',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='classification',
            name='movies',
            field=models.ManyToManyField(to='movie.Movie'),
        ),
        migrations.DeleteModel(
            name='MovieClassificationBridge',
        ),
    ]
