# Generated by Django 2.1.2 on 2019-01-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20190118_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='classification',
            field=models.ManyToManyField(to='movie.Classification'),
        ),
    ]
