# Generated by Django 2.1.2 on 2019-01-18 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20190118_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieClassificationBridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='classification',
        ),
        migrations.AddField(
            model_name='classification',
            name='movies',
            field=models.ManyToManyField(to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='movieclassificationbridge',
            name='classification_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Classification'),
        ),
        migrations.AddField(
            model_name='movieclassificationbridge',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie'),
        ),
    ]
